package edu.itz.ejercicios.vistas;

import edu.itz.ejercicios.controles.Control;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTextArea;

/**
 *
 * @author Rapid
 */
public class Ventana extends javax.swing.JFrame {
    Control c;
    

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        c=new Control(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtContenido = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        lblarchivo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtsalida = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAbrir = new javax.swing.JMenuItem();
        mnuClean = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnucuenta = new javax.swing.JMenuItem();
        mnuhexadecimal = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtContenido.setColumns(20);
        txtContenido.setRows(5);
        jScrollPane1.setViewportView(txtContenido);

        jLabel1.setText("Archivo:");

        txtsalida.setEditable(false);
        txtsalida.setColumns(20);
        txtsalida.setRows(5);
        jScrollPane2.setViewportView(txtsalida);

        jMenu1.setText("Archivo");

        mnuAbrir.setText("Abrir");
        mnuAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAbrir);

        mnuClean.setText("Limpiar");
        mnuClean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCleanActionPerformed(evt);
            }
        });
        jMenu1.add(mnuClean);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Procesar");

        mnucuenta.setText("Cuenta");
        mnucuenta.addActionListener((java.awt.event.ActionEvent evt) -> {
            mnucuentaActionPerformed(evt);
        });
         mnuhexadecimal.setText("Hexadecimal");
        mnuhexadecimal.addActionListener((java.awt.event.ActionEvent evt) -> {
            mnuhexadecimalActionPerformed(evt);
        });
        jMenu3.add(mnucuenta);
        JMenuItem add = jMenu3.add(mnuhexadecimal);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Acerca de");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblarchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblarchivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void mnuAbrirActionPerformed(java.awt.event.ActionEvent evt) {                                         
      c.abrirArchivo();
      
    }                                        

    private void mnuCleanActionPerformed(java.awt.event.ActionEvent evt) {                                         
        c.limpiar();
    }                                        

    private void mnucuentaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        //c.contar();
        c.IdConAFD();
    }   
    private void mnuhexadecimalActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        c.validarHexadecimal(); 
    }
                                        

    public JTextArea getTxtContenido() {
        return txtContenido;
    }

    public JLabel getLblarchivo() {
        return lblarchivo;
    }

    public JTextArea getTxtsalida() {
        return txtsalida;
        
    }
    
    

   

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblarchivo;
    private javax.swing.JMenuItem mnuAbrir;
    private javax.swing.JMenuItem mnuClean;
    private javax.swing.JMenuItem mnucuenta;
    private javax.swing.JMenuItem mnuhexadecimal;
    private javax.swing.JTextArea txtContenido;
    private javax.swing.JTextArea txtsalida;
    // End of variables declaration                   

    public Object getTxtSalida() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}



